name: CI - Docker Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  docker-build-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image to validate
        run: docker build -t mathatoms-website ./homepage
